version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.10-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mars_db
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge